name: Build and push docker to registry

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push-docker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Call action get-ref-properties
        id: get-ref-properties
        uses: Cardinal-Cryptography/github-actions/get-ref-properties@v7
      
      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1

      - name: Build and push docker image
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: app
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/feature-preview-app:${{ steps.get-ref-properties.outputs.sha }}
